baseURL = 'https://duanjls.github.io/myblog/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
hasCJKlanguage = true
publishDir = 'docs'
title = '我的全新 Hugo 网站'
canonifyurls = true

theme = "FeelIt"

[params]
version = "1.0.X"
description = "这是我的全新 Hugo 网站"
keywords = ["Theme", "Hugo"]
defaultTheme = "auto"
dateFormat = "2006-01-02"

[params.header]
 desktopMode = "fixed"
  mobileMode = "auto"

[params.header.title]
      logo = "favicon.ico"
      name = "DuansBlog"
      pre = ""
      post = ""
      typeit = false
      rss = true

[params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2019
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

[params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

[params.about]
    enable = true
    param = true
    paramTitle = "个人信息"
    description = "[FeelIt](https://github.com/khusika/FeelIt) 是一个由 [Khusika](https://khusika.dev) 开发的**简洁**、**优雅**且**高效**的 [Hugo](https://gohugo.io/) 博客主题。 它的原型基于 [LoveIt 主题](https://github.com/dillonzq/LoveIt), [LeaveIt 主题](https://github.com/liuzc/LeaveIt), 和 [KeepIt 主题](https://github.com/Fastbyte01/KeepIt)。"
    [[params.about.status]]
      faIcon = "fa-solid fa-building"
      title = "公司"
      desc = "FeelIt"
    [[params.about.status]]
      faIcon = "fa-solid fa-briefcase fa-fw"
      title = "职业"
      desc = "自由职业者"
    [[params.about.status]]
      title = "地点"
      faIcon = "fa-solid fa-map-marker-alt"
      desc = "地球"

[[params.about.parameter]]
      language = "UI/UX"
      level = "80"
    [[params.about.parameter]]
      language = "HTML"
      level = "70"
    [[params.about.parameter]]
      language = "Go"
      level = "60"

[params.home]
    rss = 10

[params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/头像.jpg"
      title = "DuansBlog"
      subtitle = "这是我的全新 Hugo 网站"
      typeit = true
      social = true
      disclaimer = ""


[languages]
  [languages.en]
    weight = 1
    title = "My New Hugo Site"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3

  [languages.zh-cn]
    weight = 2
    title = "我的全新 Hugo 网站"
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
      [[languages.zh-cn.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 4

  [languages.fr]
    weight = 3
    title = "Mon nouveau site Hugo"
    languageCode = "fr"
    languageName = "Français"
    [[languages.fr.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Postes"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Balises"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.fr.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Catégories"
      url = "/categories/"
      title = ""
      weight = 3

[params.search]
  enable = true
    type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 50
  highlightTag = "em"
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""