baseURL = 'https://duanjls.github.io/myblog/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
hasCJKlanguage = true
publishDir = 'docs'
title = '我的全新 Hugo 网站'

theme = "FeelIt"

[params]
version = "1.0.X"

[menu]
[[menu.main]]
identifier = "posts"
pre = ""
name = "Blog"
url = "/posts/"
title = "我的博客"
weight = 1
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = "标签"
weight = 2
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = "分类"
weight = 3
[markup]
[markup.highlight]
noClasses = false